# Site settings
title: MiUncle Blog
SEOTitle: MiUncle Blog
header-img: img/WestLake.jpg
email: 744784681@qq.com
description: "To be a good coder"
keyword: "MI, MiUncle Blog, DDK的博客, MiUncle, 杜定坤,Unity,Cocos,iOS,Android"
url: "http://kaifone.com"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/DuPrince/DuPrince.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "除了奋斗，别无选择!"
sidebar-avatar: /img/AboutMyHeadPhoto.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
github_username:    DuPrince

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 2a7916c6b2804cd4dc14                            #生成的clientID
  clientSecret: f850216973e642a6994c506aec430147833a8011    #生成的clientSecret
  repo: DuPrince.github.io    #仓库名称
  owner: DuPrince    #github用户名
  admin: MiUncle
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 统计
# Analytics settings
# Baidu Analytics
ba_track_id: dbe87793a8b524e508ca4ef646391176

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "Lukyes's Blog",
        href: "http://blog.lukye.me"
    },
    {
        title: "UWA 官网",
        href: "https://www.uwa4d.com/"
    },
    {
        title: "Unity 官网",
        href: "https://unity3d.com/cn"
    }
    ,
    {
        title: "LeetCode 官网",
        href: "https://unity3d.com/cn"
    }
]
